development:
  adapter: postgresql
  encoding: unicode
  database: library_development
  pool: 5
  timeout: 5000
  host: 'localhost'
  username: library
  password: library2019

test:
  adapter: postgresql
  encoding: unicode
  database: library_test
  pool: 5
  timeout: 5000
  host: 'localhost'
  username: library
  password: library2019